apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: simple-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: simple-device-plugin
  template:
    metadata:
      labels:
        name: simple-device-plugin
    spec:
      hostNetwork: true
      containers:
      - name: simple-device-plugin
        image: example.com/simple-device-plugin:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins